/* m42-help.c - see m42-help.h
 *
 * Copyright (C) 2026 The math42 authors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include "m42-help.h"

#include <string.h>

static const M42Function FUNCTIONS[] = {
  /* --- calculus --------------------------------------------------- */
  { "D", NULL, "D[f, x]", "the derivative of f with respect to x; D[f, {x, n}] takes it n times", "Calculus" },
  { "Integrate", "int", "Integrate[f, x]", "the antiderivative, or Integrate[f, {x, a, b}] between bounds", "Calculus" },
  { "NIntegrate", "quad", "NIntegrate[f, {x, a, b}]", "the integral by Simpson's rule, never symbolically", "Calculus" },
  { "Limit", NULL, "Limit[f, x -> a]", "the value f closes in on at a, or at Infinity", "Calculus" },
  { "Series", "Taylor", "Series[f, {x, a, n}]", "the Taylor polynomial of f about a, to order n", "Calculus" },
  { "NDSolve", "ode45", "NDSolve[f, {x, a, b}, y0]", "solves y' = f(x, y) by Runge-Kutta and returns the points", "Calculus" },
  { "DSolve", "dsolve", "DSolve[a y'' + b y' + c y == f, y, x]", "the general solution, or the one that fits y[0] == 1 and y'[0] == 0", "Calculus" },
  { "RSolve", "rsolve", "RSolve[{a[n] == a[n-1] + a[n-2], a[0] == 0, a[1] == 1}, a, n]", "the closed form of a recurrence, by its characteristic roots", "Calculus" },

  /* --- several variables -------------------------------------------- */
  { "Grad", "gradient", "Grad[f, {x, y}]", "the vector of first derivatives", "Several variables" },
  { "Div", "divergence", "Div[{p, q}, {x, y}]", "the divergence of a field", "Several variables" },
  { "Curl", "curl", "Curl[{p, q, r}, {x, y, z}]", "the curl of a field in three dimensions", "Several variables" },
  { "Laplacian", "laplacian", "Laplacian[f, {x, y}]", "the sum of the second derivatives", "Several variables" },
  { "Hessian", "hessian", "Hessian[f, {x, y}]", "the matrix of second derivatives", "Several variables" },
  { "Jacobian", "jacobian", "Jacobian[{f, g}, {x, y}]", "the matrix of first derivatives of a map", "Several variables" },

  /* --- algebra ---------------------------------------------------- */
  { "Expand", "expand", "Expand[e]", "multiplies out the brackets and gathers like terms", "Algebra" },
  { "Factor", "factor", "Factor[p]", "writes a polynomial as a product of its factors", "Algebra" },
  { "Simplify", "simplify", "Simplify[e]", "folds the constants and drops the identities", "Algebra" },
  { "Solve", "NSolve", "Solve[lhs == rhs, x]", "every root of a polynomial; a list of linear equations and a list of unknowns solves a system", "Algebra" },
  { "FindRoot", "fzero", "FindRoot[f, {x, x0}]", "one root, from a starting point, by Newton's method", "Algebra" },
  { "FindMinimum", "fminsearch", "FindMinimum[f, {x, x0}]", "{value, {x -> where}} at the bottom of the curve", "Algebra" },
  { "FindMaximum", NULL, "FindMaximum[f, {x, a, b}]", "the same at the top", "Algebra" },
  { "fminbnd", NULL, "fminbnd(f, a, b)", "where the lowest point is, between two ends", "Algebra" },
  { "Sum", NULL, "Sum[f, {i, a, b}]", "the sum of f as i runs from a to b", "Algebra" },
  { "Coefficient", NULL, "Coefficient[p, x, n]", "the number in front of x^n", "Algebra" },
  { "CoefficientList", NULL, "CoefficientList[p, x]", "every coefficient, lowest power first", "Algebra" },
  { "Exponent", NULL, "Exponent[p, x]", "the highest power of x in it", "Algebra" },
  { "Collect", "collect", "Collect[e, x]", "gathered by the powers of x", "Algebra" },
  { "Together", NULL, "Together[e]", "a sum of fractions written over one denominator", "Algebra" },
  { "Apart", "partfrac", "Apart[e, x]", "a fraction split into partial fractions", "Algebra" },
  { "PolynomialQuotient", "deconv", "PolynomialQuotient[a, b, x]", "the whole part of one polynomial over another", "Algebra" },
  { "PolynomialRemainder", NULL, "PolynomialRemainder[a, b, x]", "what is left over", "Algebra" },
  { "PolynomialGCD", NULL, "PolynomialGCD[a, b, x]", "the greatest common divisor, by Euclid", "Algebra" },
  { "Product", NULL, "Product[f, {i, a, b}]", "the product of f as i runs from a to b", "Algebra" },

  { "Timing", "tic", "Timing[expr]", "how long it took, with the answer", "Calculus" },

  /* --- transforms --------------------------------------------------- */
  { "LaplaceTransform", "laplace", "LaplaceTransform[f, t, s]", "by the table: powers, exponentials, sines, with the shift", "Transforms" },
  { "InverseLaplaceTransform", "ilaplace", "InverseLaplaceTransform[F, s, t]", "back again, by partial fractions", "Transforms" },
  { "FourierSeries", NULL, "FourierSeries[f, {x, a, b}, n]", "the series to n terms, as an expression you can plot", "Transforms" },
  { "FourierCoefficient", NULL, "FourierCoefficient[f, {x, a, b}, n]", "a0 and the pairs {an, bn}", "Transforms" },
  { "Fourier", NULL, "Fourier[list]", "the discrete transform, divided by the square root of the length", "Transforms" },
  { "InverseFourier", NULL, "InverseFourier[list]", "and back again", "Transforms" },
  { "fft", NULL, "fft(list)", "the same transform under MATLAB's convention, unnormalised", "Transforms" },
  { "ifft", NULL, "ifft(list)", "and back, divided by the length", "Transforms" },

  /* --- numbers ---------------------------------------------------- */
  { "N", "double", "N[x]", "the decimal value: N[1/3] is 0.333333333333333", "Numbers" },
  { "Rationalize", NULL, "Rationalize[x]", "the fraction a decimal is closest to", "Numbers" },
  { "Numerator", NULL, "Numerator[q]", "the top of an exact fraction", "Numbers" },
  { "Denominator", NULL, "Denominator[q]", "the bottom of an exact fraction", "Numbers" },
  { "Abs", "abs", "Abs[x]", "the size of a number, or the modulus of a complex one", "Numbers" },
  { "Sign", "sign", "Sign[x]", "-1, 0 or 1", "Numbers" },
  { "Round", "round", "Round[x]", "to the nearest whole number", "Numbers" },
  { "Floor", "floor", "Floor[x]", "down to a whole number", "Numbers" },
  { "Ceiling", "ceil", "Ceiling[x]", "up to a whole number", "Numbers" },
  { "IntegerPart", "fix", "IntegerPart[x]", "the part before the point", "Numbers" },
  { "FractionalPart", NULL, "FractionalPart[x]", "the part after the point", "Numbers" },
  { "Mod", "mod", "Mod[a, b]", "the remainder of a divided by b", "Numbers" },
  { "Quotient", "idivide", "Quotient[a, b]", "how many whole times b goes into a", "Numbers" },
  { "GCD", "gcd", "GCD[a, b]", "the greatest common divisor", "Numbers" },
  { "LCM", "lcm", "LCM[a, b]", "the least common multiple", "Numbers" },
  { "Binomial", "nchoosek", "Binomial[n, k]", "how many ways k things can be chosen from n", "Numbers" },
  { "Factorial", "factorial", "Factorial[n]", "n!, exactly however many digits it takes", "Numbers" },
  { "Gamma", "gamma", "Gamma[x]", "the gamma function, factorial's continuation", "Numbers" },
  { "PrimeQ", "isprime", "PrimeQ[n]", "whether n is prime", "Numbers" },
  { "Prime", NULL, "Prime[n]", "the nth prime", "Numbers" },
  { "Fibonacci", NULL, "Fibonacci[n]", "the nth Fibonacci number, exactly however large", "Numbers" },
  { "RandomReal", "rand", "RandomReal[]", "a number between 0 and 1, or RandomReal[{a, b}]", "Numbers" },
  { "RandomInteger", "randi", "RandomInteger[{a, b}]", "a whole number between a and b", "Numbers" },
  { "randn", NULL, "randn(n)", "numbers from the normal distribution", "Numbers" },
  { "Chop", NULL, "Chop[x]", "a number too small to matter becomes zero", "Numbers" },
  { "Round", "round", "Round[x, dx]", "to the nearest multiple of dx", "Numbers" },
  { "rem", NULL, "rem(a, b)", "the remainder, keeping the sign of a", "Numbers" },

  /* --- complex ---------------------------------------------------- */
  { "Re", "real", "Re[z]", "the real part", "Complex numbers" },
  { "Im", "imag", "Im[z]", "the imaginary part", "Complex numbers" },
  { "Conjugate", "conj", "Conjugate[z]", "the complex conjugate", "Complex numbers" },
  { "Arg", "angle", "Arg[z]", "the angle a complex number makes", "Complex numbers" },

  /* --- functions of one number ------------------------------------ */
  { "Sin", "sin", "Sin[x]", "the sine, in radians", "Functions" },
  { "Cos", "cos", "Cos[x]", "the cosine, in radians", "Functions" },
  { "Tan", "tan", "Tan[x]", "the tangent, in radians", "Functions" },
  { "ArcSin", "asin", "ArcSin[x]", "the angle whose sine is x", "Functions" },
  { "ArcCos", "acos", "ArcCos[x]", "the angle whose cosine is x", "Functions" },
  { "ArcTan", "atan", "ArcTan[x]", "the angle whose tangent is x", "Functions" },
  { "Sinh", "sinh", "Sinh[x]", "the hyperbolic sine", "Functions" },
  { "Cosh", "cosh", "Cosh[x]", "the hyperbolic cosine", "Functions" },
  { "Tanh", "tanh", "Tanh[x]", "the hyperbolic tangent", "Functions" },
  { "Exp", "exp", "Exp[x]", "e to the power x", "Functions" },
  { "Log", "log", "Log[x]", "the natural logarithm; Log10 and Log2 are there too", "Functions" },
  { "Sqrt", "sqrt", "Sqrt[x]", "the square root", "Functions" },

  /* --- asking what a thing is -------------------------------------- */
  { "Head", "class", "Head[expr]", "Integer, Rational, Real, Complex, String, List, Symbol", "Kinds" },
  { "NumberQ", "isnumeric", "NumberQ[x]", "whether it is a number", "Kinds" },
  { "IntegerQ", "isinteger", "IntegerQ[x]", "whether it is a whole number, exactly", "Kinds" },
  { "ListQ", "iscell", "ListQ[x]", "whether it is a list", "Kinds" },
  { "MatrixQ", "ismatrix", "MatrixQ[x]", "whether it is a list of equal rows", "Kinds" },
  { "StringQ", "ischar", "StringQ[x]", "whether it is a string", "Kinds" },
  { "EvenQ", NULL, "EvenQ[n]", "whether a whole number is even; OddQ asks the other way", "Kinds" },
  { "SameQ", "isequal", "SameQ[a, b]", "whether two values are the same", "Kinds" },
  { "isempty", NULL, "isempty(x)", "whether a list or string holds nothing", "Kinds" },
  { "ndims", NULL, "ndims(x)", "how deeply a list is nested", "Kinds" },

  /* --- lists ------------------------------------------------------ */
  { "Range", "linspace", "Range[n]", "{1, 2, ... n}; Range[a, b, step] and a:b:c do the same", "Lists" },
  { "Table", NULL, "Table[f, {i, a, b}]", "a list of f as i runs; more iterators nest the lists", "Lists" },
  { "Length", "length", "Length[list]", "how many items it holds", "Lists" },
  { "Total", "sum", "Total[list]", "the sum; of a matrix, the vector of its column sums", "Lists" },
  { "Mean", "mean", "Mean[list]", "the average", "Lists" },
  { "Median", "median", "Median[list]", "the middle value", "Lists" },
  { "Variance", "var", "Variance[list]", "the variance", "Lists" },
  { "StandardDeviation", "std", "StandardDeviation[list]", "the standard deviation", "Lists" },
  { "Max", "max", "Max[list]", "the largest", "Lists" },
  { "Min", "min", "Min[list]", "the smallest", "Lists" },
  { "Sort", "sort", "Sort[list]", "in order, smallest first", "Lists" },
  { "Reverse", "flip", "Reverse[list]", "back to front", "Lists" },
  { "Flatten", NULL, "Flatten[list]", "one list, however deeply it was nested", "Lists" },
  { "Join", "horzcat", "Join[a, b]", "one list after another", "Lists" },
  { "Take", NULL, "Take[list, n]", "the first n, or the last n when n is negative", "Lists" },
  { "Drop", NULL, "Drop[list, n]", "all but the first n", "Lists" },
  { "Partition", NULL, "Partition[list, n]", "cut into pieces of n", "Lists" },
  { "First", NULL, "First[list]", "the first item", "Lists" },
  { "Last", NULL, "Last[list]", "the last item", "Lists" },
  { "Rest", NULL, "Rest[list]", "all but the first", "Lists" },
  { "Append", NULL, "Append[list, x]", "the list with x on the end", "Lists" },
  { "Count", NULL, "Count[list, x]", "how many match: a value, or _ , or _Integer and its kind", "Lists" },
  { "Cases", NULL, "Cases[list, _Integer]", "the items that match a pattern", "Lists" },
  { "Clear", "clear", "Clear[f]", "forgets a name and all that was defined for it", "Lists" },
  { "ClearAll", NULL, "ClearAll[f]", "the same as Clear", "Lists" },
  { "DeleteCases", NULL, "DeleteCases[list, _String]", "the items that do not match", "Lists" },
  { "MatchQ", NULL, "MatchQ[x, _Integer]", "whether one value matches a pattern", "Lists" },
  { "FreeQ", NULL, "FreeQ[x^2 + 1, Sin[_]]", "whether a shape is nowhere in an expression", "Lists" },
  { "ReplaceAll", NULL, "ReplaceAll[expr, x_^2 -> x]", "the /. operator under its own name", "Lists" },
  { "ReplaceRepeated", NULL, "ReplaceRepeated[expr, rules]", "//., which goes on until nothing changes", "Lists" },
  { "Position", "find", "Position[list, x]", "where x appears; find gives where a list is not zero", "Lists" },
  { "Tally", NULL, "Tally[list]", "each distinct value with how often it appears", "Lists" },
  { "Union", "union", "Union[a, b]", "everything in either, once each", "Lists" },
  { "Intersection", "intersect", "Intersection[a, b]", "what is in both", "Lists" },
  { "Complement", "setdiff", "Complement[a, b]", "what is in the first and not the second", "Lists" },
  { "Accumulate", "cumsum", "Accumulate[list]", "the running totals", "Lists" },
  { "Differences", "diff", "Differences[list]", "the step from each item to the next", "Lists" },
  { "AnyTrue", "any", "AnyTrue[list]", "whether anything in it is true", "Lists" },
  { "AllTrue", "all", "AllTrue[list]", "whether everything in it is true", "Lists" },
  { "repmat", NULL, "repmat(list, n)", "the list laid end to end n times", "Lists" },
  { "fliplr", NULL, "fliplr(m)", "each row turned around; flipud turns the rows around", "Lists" },
  { "cumprod", NULL, "cumprod(list)", "the running products", "Lists" },
  { "logspace", NULL, "logspace(a, b, n)", "n points spread evenly by powers of ten", "Lists" },
  { "RandomChoice", "randsample", "RandomChoice[list]", "one of them, at random; RandomSample takes several", "Lists" },
  { "SortBy", "sortby", "SortBy[list, f]", "in the order f puts them", "Lists" },
  { "Ordering", "sortindex", "Ordering[list]", "where each item would go if the list were sorted", "Lists" },
  { "Split", NULL, "Split[list]", "runs of equal neighbours, each its own list", "Lists" },
  { "DeleteDuplicates", "unique", "DeleteDuplicates[list]", "each distinct value once, in the order it first appears", "Lists" },
  { "MemberQ", "ismember", "MemberQ[list, x]", "whether x is in it", "Lists" },
  { "MapThread", NULL, "MapThread[f, {a, b}]", "f across the lists, one item from each at a time", "Lists" },
  { "Outer", NULL, "Outer[f, a, b]", "every pairing of the two lists", "Lists" },
  { "Array", NULL, "Array[f, n]", "{f[1], f[2], ... f[n]}", "Lists" },
  { "Tuples", NULL, "Tuples[list, k]", "every way of choosing k of them, order mattering", "Lists" },
  { "Riffle", NULL, "Riffle[list, x]", "x put between each pair", "Lists" },
  { "RotateLeft", NULL, "RotateLeft[list, n]", "shifted round; RotateRight goes the other way", "Lists" },
  { "Most", NULL, "Most[list]", "all but the last", "Lists" },
  { "Prepend", NULL, "Prepend[list, x]", "x put on the front", "Lists" },
  { "Insert", NULL, "Insert[list, x, n]", "x put in at the nth place", "Lists" },
  { "Delete", NULL, "Delete[list, n]", "the nth taken out", "Lists" },
  { "meshgrid", NULL, "meshgrid(x, y)", "the two grids MATLAB makes from two ranges", "Lists" },

  /* --- matrices --------------------------------------------------- */
  { "Dot", "mtimes", "Dot[a, b]", "matrix multiplication, also written a . b", "Matrices" },
  { "Transpose", "transpose", "Transpose[m]", "rows for columns, also written m'", "Matrices" },
  { "Det", "det", "Det[m]", "the determinant", "Matrices" },
  { "Inverse", "inv", "Inverse[m]", "the inverse matrix", "Matrices" },
  { "LinearSolve", "mldivide", "LinearSolve[a, b]", "solves a x = b, also written a \\ b", "Matrices" },
  { "Eigenvalues", "eig", "Eigenvalues[m]", "by Jacobi rotations if symmetric, the QR iteration if not", "Matrices" },
  { "Eigenvectors", NULL, "Eigenvectors[m]", "one to a row; symmetric matrices only", "Matrices" },
  { "MatrixPower", "mpower", "MatrixPower[m, k]", "the matrix multiplied by itself k times", "Matrices" },
  { "Rank", "rank", "Rank[m]", "how many rows are independent", "Matrices" },
  { "Tr", "trace", "Tr[m]", "the sum down the diagonal", "Matrices" },
  { "Norm", "norm", "Norm[v]", "the length of a vector", "Matrices" },
  { "Cross", "cross", "Cross[a, b]", "the cross product of two vectors of three", "Matrices" },
  { "IdentityMatrix", "eye", "IdentityMatrix[n]", "ones down the diagonal", "Matrices" },
  { "DiagonalMatrix", "diag", "DiagonalMatrix[v]", "a vector along a diagonal, or a matrix's diagonal out", "Matrices" },
  { "ArrayReshape", "reshape", "ArrayReshape[list, {r, c}]", "the same numbers in a new shape", "Matrices" },
  { "Dimensions", "size", "Dimensions[m]", "how big it is; size(m, 1) asks for one of them", "Matrices" },
  { "ConstantArray", NULL, "ConstantArray[x, {r, c}]", "a matrix of one value; zeros and ones are shorthands", "Matrices" },
  { "RowReduce", "rref", "RowReduce[m]", "the reduced row echelon form", "Matrices" },
  { "NullSpace", "null", "NullSpace[m]", "a basis for what the matrix sends to nothing", "Matrices" },
  { "Orthogonalize", "orth", "Orthogonalize[vectors]", "the same space, at right angles and of length one", "Matrices" },
  { "LeastSquares", "lscov", "LeastSquares[a, b]", "the answer that comes closest when there is none exactly", "Matrices" },
  { "CharacteristicPolynomial", "poly", "CharacteristicPolynomial[m, x]", "det(A - x I), as a polynomial or as its coefficients", "Matrices" },
  { "MatrixExp", "expm", "MatrixExp[m]", "the exponential of a matrix", "Matrices" },
  { "LUDecomposition", "lu", "LUDecomposition[m]", "{L, U, order} with L U the rows of m in that order", "Matrices" },
  { "QRDecomposition", "qr", "QRDecomposition[m]", "{Q, R} with m = Q R, by Gram-Schmidt", "Matrices" },
  { "SingularValueDecomposition", NULL, "SingularValueDecomposition[m]", "{U, S, V}", "Matrices" },
  { "SingularValueList", "svd", "SingularValueList[m]", "the singular values, largest first", "Matrices" },
  { "PseudoInverse", "pinv", "PseudoInverse[m]", "the inverse where there is one, the nearest thing where there is not", "Matrices" },
  { "Cond", "cond", "Cond[m]", "how badly the matrix magnifies a small change", "Matrices" },
  { "Eigensystem", NULL, "Eigensystem[m]", "the eigenvalues and their vectors together", "Matrices" },
  { "Projection", NULL, "Projection[u, v]", "the part of one vector that lies along another", "Matrices" },

  /* --- polynomials, the MATLAB way: highest power first ------------ */
  { "polyval", NULL, "polyval(p, x)", "the polynomial p at x", "Polynomials" },
  { "polyfit", NULL, "polyfit(x, y, n)", "the polynomial of degree n closest to the points", "Polynomials" },
  { "Fit", NULL, "Fit[data, {1, x, x^2}, x]", "the combination of those functions closest to the points", "Polynomials" },
  { "roots", NULL, "roots(p)", "every root of the polynomial, complex ones included", "Polynomials" },
  { "conv", NULL, "conv(a, b)", "two polynomials multiplied", "Polynomials" },
  { "interp1", NULL, "interp1(x, y, at)", "a straight line between the two nearest points", "Polynomials" },
  { "Interpolation", NULL, "Interpolation[data]", "a function of one argument, drawing a line between the points", "Polynomials" },

  /* --- statistics and chance ---------------------------------------- */
  { "Correlation", "corrcoef", "Correlation[x, y]", "how closely two lists move together, between -1 and 1", "Statistics" },
  { "Covariance", "cov", "Covariance[x, y]", "how two lists vary together", "Statistics" },
  { "Quantile", "quantile", "Quantile[list, p]", "the value below which that share of the data falls", "Statistics" },
  { "Mode", "mode", "Mode[list]", "the value that turns up most often", "Statistics" },
  { "Skewness", "skewness", "Skewness[list]", "how lopsided the data is", "Statistics" },
  { "Kurtosis", "kurtosis", "Kurtosis[list]", "how heavy its tails are", "Statistics" },
  { "RootMeanSquare", "rms", "RootMeanSquare[list]", "the square root of the mean square", "Statistics" },
  { "PDF", NULL, "PDF[NormalDistribution[0, 1], x]", "the density of a distribution at a point", "Statistics" },
  { "CDF", NULL, "CDF[NormalDistribution[0, 1], x]", "how much of it lies below that point", "Statistics" },
  { "RandomVariate", NULL, "RandomVariate[NormalDistribution[0, 1], n]", "numbers drawn from a distribution", "Statistics" },
  { "NormalDistribution", NULL, "NormalDistribution[mu, sigma]", "with UniformDistribution, ExponentialDistribution, PoissonDistribution and BinomialDistribution", "Statistics" },
  { "normpdf", NULL, "normpdf(x, mu, sigma)", "the normal density, MATLAB's name for it", "Statistics" },
  { "normcdf", NULL, "normcdf(x, mu, sigma)", "the normal distribution function", "Statistics" },
  { "norminv", NULL, "norminv(p, mu, sigma)", "the value a given share falls below", "Statistics" },
  { "trapz", NULL, "trapz(y)", "the integral of a list of values by the trapezium rule", "Statistics" },
  { "cumtrapz", NULL, "cumtrapz(y)", "the same, as a running total", "Statistics" },
  { "gradient", NULL, "gradient(list)", "the slope at each point, one-sided at the ends", "Statistics" },
  { "polyder", NULL, "polyder(p)", "the derivative of a polynomial, as coefficients", "Polynomials" },
  { "polyint", NULL, "polyint(p)", "its integral, as coefficients", "Polynomials" },

  /* --- whole numbers, and counting ---------------------------------- */
  { "PowerMod", "powermod", "PowerMod[a, b, m]", "a to the power b, modulo m, without ever growing large", "Discrete" },
  { "ExtendedGCD", "gcdex", "ExtendedGCD[a, b]", "{g, {s, t}} with s a + t b = g", "Discrete" },
  { "ModularInverse", "modinv", "ModularInverse[a, m]", "what multiplies a to give 1 modulo m", "Discrete" },
  { "ChineseRemainder", "crt", "ChineseRemainder[{r1, r2}, {m1, m2}]", "the number with those remainders", "Discrete" },
  { "FactorInteger", NULL, "FactorInteger[n]", "the primes it is made of, with how many of each", "Discrete" },
  { "Divisors", "divisors", "Divisors[n]", "everything that divides it", "Discrete" },
  { "EulerPhi", "totient", "EulerPhi[n]", "how many numbers below n share no factor with it", "Discrete" },
  { "NextPrime", NULL, "NextPrime[n]", "the next prime after n", "Discrete" },
  { "PrimePi", NULL, "PrimePi[n]", "how many primes there are up to n", "Discrete" },
  { "Subsets", "powerset", "Subsets[list]", "every subset, or those of one size with Subsets[list, k]", "Discrete" },
  { "Permutations", "perms", "Permutations[list]", "every arrangement, in dictionary order", "Discrete" },
  { "CatalanNumber", NULL, "CatalanNumber[n]", "the nth Catalan number", "Discrete" },
  { "StirlingS2", NULL, "StirlingS2[n, k]", "how many ways n things fall into k parts", "Discrete" },
  { "BellB", NULL, "BellB[n]", "how many ways n things fall into any number of parts", "Discrete" },
  { "Multinomial", NULL, "Multinomial[a, b, c]", "the multinomial coefficient", "Discrete" },
  { "Xor", "xor", "Xor[p, q]", "one or the other but not both", "Discrete" },
  { "Implies", NULL, "Implies[p, q]", "false only when p holds and q does not", "Discrete" },
  { "Nand", NULL, "Nand[p, q]", "not both", "Discrete" },
  { "VertexDegrees", "degree", "VertexDegrees[m]", "how many edges meet each vertex of a graph", "Discrete" },
  { "ConnectedComponents", NULL, "ConnectedComponents[m]", "the pieces a graph falls into", "Discrete" },
  { "TransitiveClosure", NULL, "TransitiveClosure[m]", "everything reachable from everything", "Discrete" },
  { "GraphDistance", "shortestpath", "GraphDistance[m, i, j]", "the shortest way between two vertices, by Dijkstra", "Discrete" },

  /* --- programming ------------------------------------------------ */
  { "If", NULL, "If[test, then, else]", "one branch or the other", "Programming" },
  { "Which", NULL, "Which[t1, v1, t2, v2]", "the first branch whose test holds", "Programming" },
  { "Piecewise", NULL, "Piecewise[{{v1, when1}, {v2, when2}}, otherwise]", "a function given in pieces", "Programming" },
  { "For", NULL, "For[start, test, step, body]", "a loop written as Mathematica writes it", "Programming" },
  { "While", NULL, "While[test, body]", "a loop that runs while the test holds", "Programming" },
  { "Do", NULL, "Do[body, {i, a, b}]", "a loop over an iterator, keeping nothing", "Programming" },
  { "Module", "Block", "Module[{x, y = 1}, body]", "names local to the body", "Programming" },
  { "Map", "arrayfun", "Map[f, list]", "f applied to each item", "Programming" },
  { "Select", NULL, "Select[list, f]", "the items f says yes to", "Programming" },
  { "Fold", NULL, "Fold[f, x, list]", "f applied along the list, carrying the answer", "Programming" },
  { "Nest", NULL, "Nest[f, x, n]", "f applied to x, n times over", "Programming" },
  { "NestList", NULL, "NestList[f, x, n]", "every step of that, as a list", "Programming" },
  { "Apply", NULL, "Apply[f, list]", "the list handed to f as its arguments", "Programming" },
  { "Print", "disp", "Print[a, b]", "writes above the result", "Programming" },
  { "Names", NULL, "Names[]", "every function math42 knows, as a list of strings", "Programming" },
  { "Function", NULL, "#^2 &", "a pure function; #1 and #2 are its arguments", "Programming" },
  { "Span", NULL, "x[[2 ;; 4]]", "the part of a list between two places", "Programming" },
  { "All", NULL, "m[[All, 2]]", "every index at that level; MATLAB writes it as a bare colon", "Programming" },
  { "Information", "Help", "Information[\"Sin\"]", "what a function does; ?Sin is shorthand", "Programming" },

  /* --- strings ---------------------------------------------------- */
  { "StringJoin", "strcat", "StringJoin[a, b]", "one string after another", "Strings" },
  { "StringLength", "strlength", "StringLength[s]", "how many characters", "Strings" },
  { "ToString", "num2str", "ToString[x]", "a value written as a string", "Strings" },
  { "ToUpperCase", "upper", "ToUpperCase[s]", "in capitals", "Strings" },
  { "ToLowerCase", "lower", "ToLowerCase[s]", "in small letters", "Strings" },
  { "StringTake", NULL, "StringTake[s, n]", "the first n characters, or the last n if negative", "Strings" },
  { "StringDrop", NULL, "StringDrop[s, n]", "everything after the first n", "Strings" },
  { "StringReplace", "strrep", "StringReplace[s, from, to]", "every copy of one piece swapped for another", "Strings" },
  { "StringSplit", "strsplit", "StringSplit[s, sep]", "cut into pieces at a separator", "Strings" },
  { "StringReverse", NULL, "StringReverse[s]", "back to front", "Strings" },
  { "StringRiffle", "strjoin", "StringRiffle[list, \", \"]", "the pieces with something between them", "Strings" },
  { "StringTrim", "strtrim", "StringTrim[s]", "without the spaces at either end", "Strings" },
  { "StringContainsQ", "contains", "StringContainsQ[s, piece]", "whether a piece is in there", "Strings" },
  { "StringStartsQ", "startsWith", "StringStartsQ[s, piece]", "whether it begins that way", "Strings" },
  { "StringEndsQ", "endsWith", "StringEndsQ[s, piece]", "whether it ends that way", "Strings" },
  { "StringCount", NULL, "StringCount[s, piece]", "how many times a piece appears", "Strings" },
  { "StringPadLeft", NULL, "StringPadLeft[s, n]", "made up to n characters with spaces in front", "Strings" },
  { "StringPadRight", NULL, "StringPadRight[s, n]", "the same, with the spaces after", "Strings" },
  { "IntegerString", "dec2base", "IntegerString[255, 16]", "a whole number written in a base", "Strings" },
  { "FromDigits", "base2dec", "FromDigits[\"ff\", 16]", "the number a string spells in a base", "Strings" },
  { "StringPosition", "strfind", "StringPosition[s, piece]", "where a piece appears", "Strings" },
  { "Characters", NULL, "Characters[s]", "the string as a list of one-character strings", "Strings" },
  { "ToExpression", "str2num", "ToExpression[s]", "the string read as though it had been typed", "Strings" },
  { "str2double", NULL, "str2double(s)", "the number a string spells", "Strings" },
  { "strcmp", NULL, "strcmp(a, b)", "whether two strings are the same", "Strings" },
  { "sprintf", NULL, "sprintf(fmt, a, b)", "MATLAB formatting: %d, %f, %e, %g, %s, with widths", "Strings" },
  { "fprintf", "printf", "fprintf(fmt, a)", "the same, written above the result", "Strings" },

  /* --- graphs ----------------------------------------------------- */
  { "Plot", "fplot", "Plot[f, {x, a, b}]", "the graph of f; a list of functions draws several", "Graphs" },
  { "Plot3D", "surf", "Plot3D[f, {x, a, b}, {y, c, d}]", "a surface, drawn in projection with its mesh", "Graphs" },
  { "ParametricPlot", NULL, "ParametricPlot[{x, y}, {t, a, b}]", "the curve a moving point traces", "Graphs" },
  { "PolarPlot", "polarplot", "PolarPlot[r, {t, a, b}]", "a curve in polar coordinates", "Graphs" },
  { "ListPlot", "scatter", "ListPlot[data]", "a dot at each point", "Graphs" },
  { "ListLinePlot", "plot", "ListLinePlot[data]", "the points joined up", "Graphs" },
  { "BarChart", "bar", "BarChart[list]", "a bar for each number", "Graphs" },
  { "Histogram", "hist", "Histogram[data]", "the data in bins, as bars", "Graphs" },
  { "ContourPlot", "contour", "ContourPlot[f, {x, a, b}, {y, c, d}]", "the curves along which f keeps the same value", "Graphs" },
  { "LogPlot", "semilogy", "LogPlot[f, {x, a, b}]", "with the upright axis in powers of ten", "Graphs" },
  { "LogLinearPlot", "semilogx", "LogLinearPlot[f, {x, a, b}]", "with the level axis in powers of ten", "Graphs" },
  { "LogLogPlot", "loglog", "LogLogPlot[f, {x, a, b}]", "with both axes in powers of ten", "Graphs" },
  { "StemPlot", "stem", "StemPlot[list]", "a stalk from the axis with a dot on top", "Graphs" },
  { "StairsPlot", "stairs", "StairsPlot[list]", "held flat, then stepped", "Graphs" },
  { "DensityPlot", NULL, "DensityPlot[f, {x, a, b}, {y, c, d}]", "the same surface looked straight down on, as colour", "Graphs" },
  { "ListPlot3D", NULL, "ListPlot3D[grid]", "a surface from a grid of heights", "Graphs" },
  { "ListContourPlot", NULL, "ListContourPlot[grid]", "its contours", "Graphs" },
  { "ListDensityPlot", NULL, "ListDensityPlot[grid]", "and it looked down on", "Graphs" },
  { "Show", NULL, "Show[p, q]", "graphs laid over one another", "Graphs" },

  /* --- the ones that had been left out of this table ---------------
   *
   * A name missing from here is a name m42_function_find cannot find,
   * and a call written with round brackets and one argument is then
   * read as a multiplication instead: zeros(3) came out as 3 zeros.
   * To check for more of them, pull every name_is out of m42-eval.c
   * and look for the ones this table does not hold.
   */
  { "zeros", NULL, "zeros(n)", "a list, or a matrix, of nothing but zeros", "Matrices" },
  { "nnz", NULL, "nnz(list)", "how many of them are not zero", "Lists" },
  { "Import", "csvread", "Import[\"data.csv\"]", "a table of numbers from a file, or its text", "Lists" },
  { "Export", "csvwrite", "Export[\"data.csv\", table]", "a table written to a file", "Lists" },
  { "readmatrix", NULL, "readmatrix(\"data.csv\")", "the same, MATLAB's name for reading", "Lists" },
  { "writematrix", NULL, "writematrix(table, \"data.csv\")", "and for writing", "Lists" },
  { "ReadString", NULL, "ReadString[\"notes.txt\"]", "a whole file as one string", "Strings" },
  { "Keys", NULL, "Keys[{a -> 1, b -> 2}]", "the left sides of a list of rules", "Lists" },
  { "Values", NULL, "Values[{a -> 1, b -> 2}]", "the right sides of them", "Lists" },
  { "Lookup", NULL, "Lookup[rules, key]", "what one key stands for, or a third argument when it is not there", "Lists" },
  { "Subdivide", NULL, "Subdivide[0, 1, 4]", "the way from a to b cut into n pieces, exactly", "Lists" },
  { "Rescale", NULL, "Rescale[list]", "stretched to run from 0 to 1", "Statistics" },
  { "Standardize", NULL, "Standardize[list]", "shifted and scaled to a mean of 0 and a spread of 1", "Statistics" },
  { "ArrayDepth", "ndims", "ArrayDepth[list]", "how deeply the lists are nested", "Lists" },
  { "NumberForm", NULL, "NumberForm[Pi, 5]", "a number written to so many figures, as a string", "Strings" },
  { "Positive", NULL, "Positive[x]", "whether it is more than nothing", "Kinds" },
  { "Negative", NULL, "Negative[x]", "whether it is less than nothing", "Kinds" },
  { "NonNegative", NULL, "NonNegative[x]", "whether it is nothing or more", "Kinds" },
  { "NonPositive", NULL, "NonPositive[x]", "whether it is nothing or less", "Kinds" },
  { "Break", NULL, "Break[]", "leaves the loop it is in", "Programming" },
  { "Continue", NULL, "Continue[]", "goes straight to the next turn of the loop", "Programming" },
  { "Return", NULL, "Return[x]", "leaves the function it is in, with an answer", "Programming" },
  { "Switch", "switch", "Switch[x, 1, \"one\", _, \"other\"]", "the first shape x answers to, and what to do then", "Programming" },
  { "FullSimplify", NULL, "FullSimplify[e]", "Simplify, which already tries what it knows", "Algebra" },
  { "FoldList", NULL, "FoldList[Plus, 0, list]", "every step of the folding, not just the last", "Lists" },
  { "FixedPoint", NULL, "FixedPoint[Cos, 1.0]", "applied over and over until it stops moving", "Lists" },
  { "FixedPointList", NULL, "FixedPointList[Cos, 1.0]", "the same, keeping every step", "Lists" },
  { "NestWhile", NULL, "NestWhile[#/2 &, 100, # > 1 &]", "applied while a test still holds", "Lists" },
  { "NestWhileList", NULL, "NestWhileList[#/2 &, 100, # > 1 &]", "the same, keeping every step", "Lists" },
  { "Gather", NULL, "Gather[{1, 2, 1}]", "the ones that are the same, put together", "Lists" },
  { "GatherBy", NULL, "GatherBy[list, f]", "put together by what f makes of them", "Lists" },
  { "GroupBy", NULL, "GroupBy[list, EvenQ]", "the same, as key -> the ones with it", "Lists" },
  { "Through", NULL, "Through[{Sin, Cos}, 0]", "several functions given the same argument", "Lists" },
  { "hypot", NULL, "hypot(a, b)", "the long side of a right triangle", "Numbers" },
  { "nthroot", NULL, "nthroot(x, n)", "the real nth root, negative numbers included", "Numbers" },
  { "deg2rad", "rad2deg", "deg2rad(180)", "degrees into radians, and back the other way", "Numbers" },
  { "primes", NULL, "primes(50)", "every prime up to n, by the sieve", "Discrete" },
  { "UpperTriangularize", "triu", "UpperTriangularize[m]", "the triangle above the diagonal, the rest zero", "Matrices" },
  { "LowerTriangularize", "tril", "LowerTriangularize[m]", "the triangle below it", "Matrices" },
  { "KroneckerProduct", "kron", "KroneckerProduct[a, b]", "every element of one times the whole of the other", "Matrices" },
  { "rot90", NULL, "rot90(m)", "a matrix turned a quarter turn to the left", "Matrices" },
  { "sortrows", NULL, "sortrows(m)", "the rows put in order of the first column", "Matrices" },
  { "interp1", NULL, "interp1(x, y, xq)", "a straight line drawn between the points either side", "Lists" },
  { "ones", NULL, "ones(n)", "the same, of nothing but ones", "Matrices" },
  { "prod", NULL, "prod(list)", "everything in it multiplied together", "Lists" },
  { "numel", NULL, "numel(list)", "how many items, MATLAB's spelling", "Lists" },
  { "flipud", NULL, "flipud(m)", "the rows of a matrix the other way up", "Matrices" },
  { "circshift", NULL, "circshift(list, n)", "shifted along, with what falls off the end put back at the front", "Lists" },
  { "RotateRight", "circshift", "RotateRight[list, n]", "the same, written the other way", "Lists" },
  { "RandomSample", "randsample", "RandomSample[list, n]", "n of them, drawn without putting any back", "Lists" },
  { "heaviside", "UnitStep", "heaviside(x)", "0 below zero and 1 above it", "Functions" },
  { "UnitStep", "heaviside", "UnitStep[x]", "the step, Mathematica's spelling", "Functions" },
  { "Boole", NULL, "Boole[test]", "1 when the test holds and 0 when it does not", "Functions" },
  { "Clip", NULL, "Clip[x, {lo, hi}]", "held between two ends", "Functions" },
  { "Beta", "beta", "Beta[a, b]", "the beta function", "Functions" },
  { "logical", NULL, "logical(x)", "1 for anything that is not zero", "Kinds" },
  { "TrueQ", NULL, "TrueQ[x]", "whether it is true", "Kinds" },
  { "NumericQ", "isnumeric", "NumericQ[x]", "whether it is a number of any kind", "Kinds" },
  { "VectorQ", "isvector", "VectorQ[x]", "whether it is a list with nothing nested in it", "Kinds" },
  { "OddQ", NULL, "OddQ[n]", "whether a whole number is odd", "Kinds" },
  { "Derivative", NULL, "f'[x]", "the derivative written with a prime", "Calculus" },
  { "integral", NULL, "integral(f, a, b)", "MATLAB's numeric integral", "Calculus" },
  { "ArgMin", "argmin", "ArgMin[list]", "where the smallest one is", "Lists" },
  { "Cancel", NULL, "Cancel[e]", "a fraction with what divides out taken off", "Polynomials" },
  { "MatrixForm", NULL, "MatrixForm[m]", "a matrix shown as a grid", "Matrices" },
  { "With", NULL, "With[{x = 2}, x^2]", "a value put in and then the body worked out", "Programming" },
  { "StringForm", NULL, "StringForm[\"`` and ``\", a, b]", "a template with the values dropped in", "Strings" },
  { "Plus", NULL, "Plus[a, b]", "addition by name, for Apply", "Functions" },
  { "Times", NULL, "Times[a, b]", "multiplication by name", "Functions" },
  { "Power", "power", "Power[a, b]", "one raised to the other", "Functions" },
  { "colon", NULL, "colon(a, b)", "MATLAB's a:b as a function", "Lists" },
  { "mesh", NULL, "mesh(z)", "a surface from a grid of heights", "Graphs" },
  { "title", NULL, "title(\"a title\")", "MATLAB's label for the last graph", "Graphs" },
  { "xlabel", "ylabel", "xlabel(\"x\")", "the label along an axis", "Graphs" },
  { "ylim", "xlim", "ylim({lo, hi})", "how far an axis reaches", "Graphs" },
  { "PlotLabel", NULL, "Plot[f, {x, a, b}, PlotLabel -> \"a title\"]", "an option: the title over a graph", "Graphs" },
  { "AxesLabel", NULL, "AxesLabel -> {\"x\", \"y\"}", "an option: what the axes are called", "Graphs" },
  { "PlotRange", NULL, "PlotRange -> {lo, hi}", "an option: how far the upright axis reaches", "Graphs" },
  { "fmaxbnd", NULL, "fmaxbnd(f, a, b)", "where the highest point is, between two ends", "Algebra" },
  { "simplifyfraction", "Together", "simplifyfraction(e)", "over one denominator, MATLAB's spelling", "Polynomials" },

  { NULL, NULL, NULL, NULL, NULL },

};

const M42Function *
m42_functions (void)
{
  return FUNCTIONS;
}

const M42Function *
m42_function_find (const char *name)
{
  for (const M42Function *f = FUNCTIONS; f->name != NULL; f++)
    if (strcmp (f->name, name) == 0 || (f->matlab != NULL && strcmp (f->matlab, name) == 0))
      return f;
  return NULL;
}
